services:
  devita-ai:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
      - .env.dev
    container_name: devita-ai
    ports:
      - "8000:8000"
    depends_on:
      - chroma
    networks:
      - ai
  chroma:
    image: chromadb/chroma
    container_name: chroma
    ports:
      - "8001:8000"
    networks:
      - ai

networks:
  ai:
    driver: bridge